spring:
  application:
    name: consul-demo

config:
  redis:
    addr: 127.0.0.1:6379
    retry: 3
    expire: 2592000


#  data:
#    elasticsearch:
#      cluster-name: elasticsearch #默认即为 elasticsearch
#      cluster-nodes: 127.0.0.1:9300 #配置es节点信息，逗号分隔，如果没有指定，则启动ClientNode


#  cloud:
#    consul:
#      host: 192.168.139.204
#      port: 8500
#      discovery:
#        healthCheckPath: /
#        healthCheckInterval: 5s