spring:
#redis start
  redis:
    database: 0
    host: 192.168.139.204
    port: 6379
  data:
    elasticsearch:
      cluster-nodes: 127.0.0.1:9300
      cluster-name: elasticsearch_weile

#redis end



#auto config start

test:
  info: infovalue
  info1: infovalue1

#auto config end


