spring:
#redis start
  redis:
    database: 0
    host: 52.42.244.218
    port: 6379
  data:
    elasticsearch:
      cluster-nodes: 192.168.187.26:9300

#redis end



#auto config start

test:
  info: infovalue
  info1: infovalue1

#auto config end


