spring:
  application:
    name: consul-demo
    port: 8081

#goods-query redis
redis:
  test:
    host: 127.0.0.1
    port: 6379
    password:
    timeout: 2000
    maxActive: 300
    maxIdle: 100
    maxWait: 1000
    testOnBorrow: true
    testWhileIdle: true



#goods-command
#config:
#  redis:
#    addr: 127.0.0.1:6379
#    retry: 3
#    expire: 2592000


#  data:
#    elasticsearch:
#      cluster-name: elasticsearch #默认即为 elasticsearch
#      cluster-nodes: 127.0.0.1:9300 #配置es节点信息，逗号分隔，如果没有指定，则启动ClientNode


#  cloud:
#    consul:
    #      host: 192.168.139.204
#      port: 8500
#      discovery:
#        healthCheckPath: /#        healthCheckInterval: 5s
feign:
  hystrix:
    enabled: true

hystrix:
  command:
    default:
      circuitBreaker:
        enabled: true
        forceOpen: true
      execution:
        timeout:
          enabled: true



management:
  endpoints:
    web:
      exposure:
        include: "*"
